name: arcadi
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  dio: ^4.0.1
  dio_cookie_manager: ^2.0.0
  easy_mask: ^2.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  pinput: ^1.2.1
  shared_preferences: ^2.0.8
  url_launcher: ^6.0.12
  hooks_riverpod: ^0.14.0+4
  flutter_hooks: ^0.17.0

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/img/

  fonts:
    - family: ArcanaIcons
      fonts:
        - asset: assets/icons/arcana.ttf